---
title: "Team 8: Credit Chronicles "
author: "Members: Sai Krishna ,Gourab Mukherjee, Tulasi"
#date: "`r Sys.Date()`"
output:
  html_document:
    css: custom_theme.css
    code_folding: hide
---


```{r init, include=F}
# The package "ezids" (EZ Intro to Data Science) includes some helper functions we developed for the course. 
# Some of the frequently used functions are loadPkg(), xkabledply(), xkablesummary(), uzscale(), etc.
# You will need to install it (once) from GitHub.
# library(devtools)
# devtools::install_github("physicsland/ezids")
# Then load the package in your R session.
library(ezids)
```


```{r setup, include=FALSE}
# Some of common RMD options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
knitr::opts_chunk$set(warning = F, message = F)
# Can globally set option for number display format.
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
```

```{r reading_datafile_credit_card_churn.csv  , include=TRUE}
library(readr)
credit_card <- read.csv("credit_card.csv")
knitr::kable(str(credit_card))

```

```{r}
summary(credit_card)
```



```{r Column_names , include=TRUE}
column_names <- colnames(credit_card)
last_two_columns <- tail(column_names, 2)
print(column_names)
```


```{r Dropping_last_two_columns_to_get_final_dataframe , include=TRUE}

credit_card_final <- subset(credit_card,select = !colnames(credit_card) %in% last_two_columns)
head(credit_card_final,2)
```


```{r summary_on_new_dataframe  , include=TRUE}
summary(credit_card_final)
```


























