---
title: "Team 8: Credit Chronicles "
author: "Members: Sai Krishna ,Gourab Mukherjee, Tulasi"
#date: "`r Sys.Date()`"
output:
  html_document:
    css: custom_theme.css
    code_folding: hide
---


```{r init, include=F}
# The package "ezids" (EZ Intro to Data Science) includes some helper functions we developed for the course. 
# Some of the frequently used functions are loadPkg(), xkabledply(), xkablesummary(), uzscale(), etc.
# You will need to install it (once) from GitHub.
#install.packages("devtools")
#library(devtools)
#devtools::install_github("physicsland/ezids")
# Then load the package in your R session.
library(ezids)
```


```{r setup, include=FALSE}
# Some of common RMD options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
knitr::opts_chunk$set(warning = F, message = F)
# Can globally set option for number display format.
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
```
<h1 style="color: RED;"><b>DATA PREPROCESSING</b></h1>
<h1 style="color: white;"><b>LOADING DATASET & CHECKING str():</b></h1>
```{r reading_datafile_credit_card_churn.csv  , include=TRUE}
library(readr)
credit_card <- read.csv("credit_card.csv")
print(str(credit_card))


```
<h1 style="color: white;"><b>DIMENSIONS OF DATA: </b></h1>
```{r}
dim(credit_card)
```
<h1 style="color: white;"><b>SUMMARY OF DATASET:</b></h1>
```{r}
summary(credit_card)
```
<h1 style="color: white;"><b>COLUMN NAMES IN THE DATASET:</b></h1>
```{r Column_names , include=TRUE}
column_names <- colnames(credit_card)
last_two_columns <- tail(column_names, 2)
print(column_names)

```
<h1 style="color: white;"><b>DATA TYPES OF COLUMNS:</b></h1>
```{r Data_Types_of_Columns, include=TRUE}
column_data_types <- sapply(credit_card, class)
print(column_data_types)
```
<h1 style="color: white;"><b>AFTER DROPING UNNECESSARY COLUMNS:</b></h1>
```{r Dropping_last_two_columns_to_get_final_dataframe , include=TRUE}

credit_card_final <- subset(credit_card,select = !colnames(credit_card) %in% last_two_columns)
print(colnames(credit_card_final))

```
<h1 style="color: white;"><b>CHECKING FOR NULL VALUES</b></h1>
```{r}
null_counts <- colSums(is.na(credit_card_final))
print(null_counts)
```

<h1 style="color: white;"><b>REPLACING SPACES WITH NA AND CHECKING FOR NULL VALUES OR UNFILLED VALUES </b></h1>
```{r}
credit_card_final[credit_card_final == " "] <- NA
null_counts1 <- colSums(is.na(credit_card_final))
print(null_counts1)
```
<h1 style="color: white;"><b>CATEGORICAL VARIABLES:</b></h1>
```{r Categorical_Variables, include=TRUE}
library(dplyr)

# Identify categorical variables (regardless of data type)
categorical_variables <- credit_card_final %>%
  select_if(function(col) is.character(col) || is.factor(col)) %>%
  names()

print(categorical_variables)
```

